#A partir d'une image ubuntu
FROM ubuntu:18.04

#Installer le nécessaire pour faire les tests
RUN apt-get update
RUN apt-get install -y nano
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools